language: python
deploy:
  provider: heroku
  api_key:
    secure: LEfe7xtgwitMRf6TaToVBTtqBHS0tdBtRF6mDQgW9o9He6x/tjL1a8wbt/n7sMtkrsoWoiGPhByHVNS+bkVTKuVJZcJpG0OQmuM6awTAw/qKNoXVpK4ejtTomSHAlSIikwdGQwxrqjrcg13GMTqVGtQpGxfqsH/Y29IDC+5Wvlj1+G2B3y7n1rVQEHkrGCaduqovDgIm0EJxjbia7d48dAlk1D4vrB2dvMuI73oLT/BxRVghnbVgR01Z5RTZnjzBKwl7eeiR0XEnWwib3FBceKHPC6h4bKC00BP21D57oDai3fGo207IRmDdx/c0IpSo1B8t2fhVTo5y0sgBODjXzD5M58PKby3eyaR1kmlroD5+Q7KiQ9fmR1VQatxJyZ7R15uKx8lPE2R6+707LZPggIsBn1FNtj0ItjPrQF6B9j0+y3aqXjgwEN+Hu1uoI6FtAH4Egrq4+fvdKcTezxI7pC3Fyjby7NAAVJHw7ziofnjgjHvaU+4drb1Gz4VYDYyJlhvrPIoaJW3VXookFvPZJ8X5RrQ2RqlptT4YQz9pnbS0+ATSDnc8Qufk7UVEMGLN3IFbm5WiD5QCYbujEpLbvLsRA+bwPx+vpffiKuabHuLrD74XHaFXQvp7+tUg/br3Sd25KhqRVnteGo3C/J3PyeZhqDL/BYNAXvmunKxEKpY=
  app: lab11111
